### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by JamesCarzon** [vasanchez16/smokeppe_constraints#1]
Clean-up tasks

Namespace
- [ ] Consistent naming convention (camel case for classes, lowercase with underscores for functions and variables)
- [ ] Common `set_up_directories` and `save_XXX` methods for utils rather than similar in storage, inference, etc.
- [ ] Define .json template and remove .ini component if not desired.

Reproducibility
- [ ] Edit template .json
- [ ] Set-up minimal examples for both datasets
- [ ] Abstract methods for computing implausibilities and quantiles

Easily improved
- [ ] Pass arguments to the inference pipes rather than dictionaries of unknown arguments. (Get rid of reading JSON in every step.)

**Comment by JamesCarzon** [comment]
@vasanchez16, there's still a lot of redundancy in the code so it's a bit hard for me to parse the relevant methods. I'm going to use this issue to track progress on clean-up and refactor anew starting from commit `54d3d2059d` on the `dev` branch [04/24/24].

**Comment by vasanchez16** [comment]
@JamesCarzon, looks like we can move forward with this version of the code, I will probably be making some changes to add more code but I'll list those commits under this issue
